---
- ansible.builtin.import_role:
    name: fuzzymistborn.autorestic
  vars:
    autorestic_config_yaml:
      version: 2
      locations:
        home:
          from: /
          to: remote
          options:
            backup:
              exclude:
                - /backups
                - /cdrom
                - /dev
                - /lost+found
                - /media
                - /mnt
                - /proc
                - /run
                - /snap
                - /sys
                - /tank
                - /tmp
                - /var/cache
                - /var/lib/lxcfs
                - /var/run
                - /var/tmp
                - /seodrop
                - /var/www
      backends:
        remote:
          type: rest
          path: "http://{{ restic_rest_server_user_default }}:{{ restic_rest_server_password_default }}@{{ restic_rest_server_host_default }}:{{ restic_server_port_default }}/{{ inventory_hostname }}"
          key: "{{ restic_client_password_default }}"
  tags:
    - restic_client

