---
- ansible.builtin.import_role:
    name: tigattack.restic_rest_server
  vars:
    restic_rest_server_password: "{{ default_restic_rest_server_password }}"
    restic_rest_server_options:
      - --append-only
      - --prometheus
      - --prometheus-no-auth
  tags:
    - restic_rest_server
